export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_CURRENT_USER_ID = "SET_CURRENT_USER_ID";
export const UPDATE_TASKS = "UPDATE_TASKS";
