export const UPDATE_CARS = 'UPDATE_PROJECTS';
export const UPDATE_RENTALS = 'UPDATE_RENTALS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_CURRENT_USER_ID = "SET_CURRENT_USER_ID";